name: ss-search CI
env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install NPM packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint files
        run: npm run lint:all

      - name: Check formatting
        run: npm run format:check:ci

      - name: Run tests
        run: npm run test:all

      - name: Build apps
        run: npm run build:all -- --prod

      - name: Check exports
        run: npm run exports:check

      - name: Run benchmark
        if: github.ref == 'refs/heads/master'
        run: npm run benchmark

      - name: Release + Publish package
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: npm run semantic-release:all

      - name: Deploy to netlify
        if: github.ref == 'refs/heads/master'
        run: npm run netlify:deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
