name: ss-search CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install NPM packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint files
        run: npm run lint:all

      - name: Run tests
        run: npm run test:all

      - name: Build apps
        run: npm run build:all

      - name: Run benchmark
        if: github.ref == 'refs/heads/master'
        run: npm run benchmark

      - name: Release + Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: npm run semantic-release:all
